### ISSUE TITLE
Memory issue during evaluation

### ISSUE THREAD

**Issue by junhocho** [ruotianluo/Faster-RCNN-Densecap-torch#3]
The training is fine but I constantly have memory issue 
`luajit: not enough memory`

![2016-10-04 12 00 54](https://cloud.githubusercontent.com/assets/15857111/19042425/fae7c93e-89c6-11e6-80a6-8cf236f4c591.png)

it happens in `~/Faster-RCNN-Densecap-torch/eval/eval_utils.lua`
I used garbage collection functions (`collectgarbage('count')` and `collectgarbage()`) in `eval_utils.lua` to prevent memory issue but it doesn't help.
and commenting out line 90~101

``` lua
evaluator[1]:addResult(scores[1], boxes[1], gt_boxes[1], 'RPN')
for cls = 2, model.opt.num_classes do
      debugger.enter() -- use with fb.debugger
      -- index of current cls in gt_labels. if gt_labels = [20, 16] and cls = 16 --> sel_inds = 2
      sel_inds = torch.range(1,gt_labels[1]:size(1))[gt_labels[1]:eq(cls)]:long()
      -- if current cls not in gt_labels, then sel_inds:numel() = 0 which is following if-scope
      if sel_inds:numel() ~= 0 then
        cls_gt_boxes = gt_boxes[1]:index(1, sel_inds)
      end 
      evaluator[cls]:addResult(scores[cls], boxes[cls], -- table index start from 1
      cls_gt_boxes, model.opt.idx_to_cls[cls])
end 
```

Finishes evaluation part (of course unable to calculate mAP)
I saw original DenseCap code and it uses only one `evaluator` while this code has 21 evaluator for RPN + 20 objects.

How did you manage this? Any idea to prevent it?

**Comment by ruotianluo** [comment]
Check garbage doesn't help, because the reason of out of memory is because the image is too large (the memory could be very long or very wide) so that the memory usage for forwarding is too high. 
I had this problem once, but I can't remember how I fixed it. 
One option is to crop the image in the dataloader so that it will not be to long, be aware of the ground truth bounding box coordinate in this case. 
Another is you can train the network by changing the image_size option. You can constrain the longer side of the image to be less than a certain number.

**Comment by ruotianluo** [comment]
Are you sure that you are commenting out these lines? Memory out is mostly caused by forwarding in my case.
Can you keep `evaluator[1]:addResult(scores[1], boxes[1], gt_boxes[1], 'RPN')` so that we can check if we can get mAP for RPN?

**Comment by junhocho** [comment]
I am training on VOC PASCAL2012 train and evaluation on val set.

`th train-debug.lua -gciter 200 -anchor_type voc -image_size ^600 -data_h5 data/voc12.h5 -data_json data/voc12.json -learning_rate 1e-4 -optim adam`

![2016-10-04 2 27 48](https://cloud.githubusercontent.com/assets/15857111/19046913/8c76a4de-89da-11e6-87cb-1d92dcde3931.png)

I tried evaluation on RPN only. The first evaluation (5000 training) passed and the collectgarbage is even less than before. It looks too many evaluators are problem to me.

**Comment by ruotianluo** [comment]
I guess that is an issue.
Try to set val_images_use to be a smaller value. It doesn't truly solved the problem, however it could at least let your model train smoothly.

**Comment by junhocho** [comment]
Thx for the help!
But, having one more problem at 2nd evaluation after 10,000 training iter ..

![c16cfd4a-116c-4bf5-91f7-30840924dccc](https://cloud.githubusercontent.com/assets/15857111/19048025/795fb3e0-89df-11e6-9c48-9317658eeef4.png)

I would go through it by myself but posting it because this is very similart to another issue i am having. I was making seprate evaluation code but had this error at 478th val image.

```
Processed image /media/pil/DATA_linux/junhodata/VOCdevkit/VOC2012/JPEGImages/2008_001821.jpg (478 / 5823) of split 1, detected 1000 regions
0 in 2835
/home/junho/torch/install/bin/luajit: /home/junho/torch/install/share/lua/5.1/nn/Container.lua:67:

In 3 module of nn.Sequential:

/home/junho/torch/install/share/lua/5.1/torch/Tensor.lua:458: bad argument #1 to 'set' (expecting number or torch.LongTensor or torch.LongStorage at /tmp/luarocks_torch-scm-1-5676/torch7/generic/Tensor.c:1125)

stack traceback:
        [C]: in function 'set'
        /home/junho/torch/install/share/lua/5.1/torch/Tensor.lua:458: in function 'view'
        ./densecap/modules/AnchorTarget.lua:117: in function 'forward'
        ./densecap/LocalizationLayer.lua:465: in function 'f'
        ./densecap/LocalizationLayer.lua:265: in function 'timeit'
        ./densecap/LocalizationLayer.lua:464: in function <./densecap/LocalizationLayer.lua:421>
        [C]: in function 'xpcall'
        /home/junho/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/junho/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        ./densecap/DenseCapModel.lua:265: in function 'forward'
        ./densecap/DenseCapModel.lua:441: in function 'forward_backward'
        ./eval/eval_utils.lua:61: in function 'eval_split'
        evaluate_model2.lua:63: in main chunk
        [C]: in function 'dofile'
        ...unho/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.

stack traceback:
        [C]: in function 'error'
        /home/junho/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
        /home/junho/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        ./densecap/DenseCapModel.lua:265: in function 'forward'
        ./densecap/DenseCapModel.lua:441: in function 'forward_backward'
        ./eval/eval_utils.lua:61: in function 'eval_split'
        evaluate_model2.lua:63: in main chunk
        [C]: in function 'dofile'
        ...unho/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670
```

Is it coincident to have trouble only at 478th image?

**Comment by ruotianluo** [comment]
It's because there are no bbox in bound, which is weird. You could print out the xmin xmax ymin ymax, to see what's going on. Normally it should not happen because the shorter side of the image is 600.

**Comment by junhocho** [comment]
Thx! i will check it out
it's weird that training proceeds with GTX titan x but not in GTX 1080.

+) I found that ^600 options is causing the problem. I changed `-image_size ^600` option to `-image_size 600` and it successfully proceeds training. THX!
